# Generated by Django 5.2.17 on 2026-08-13 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('short_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('label_text', models.CharField(blank=True, help_text='Text printed on the bin label.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unavailable', 'Currently Unavailable'), ('to_discontinue', 'To Discontinue'), ('discontinued', 'Discontinued')], db_index=True, default='active', max_length=20)),
                ('unit', models.CharField(default='each', max_length=32)),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Restock below this.', null=True)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('supplier_part_num', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='inventory.location')),
            ],
            options={
                'ordering': ('part_number',),
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_link', models.URLField(blank=True, max_length=1000)),
                ('observed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='inventory.part')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-observed_at', '-id'),
                'indexes': [models.Index(fields=['part', '-observed_at'], name='inventory_p_part_id_7d06a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inventory', 'On floor'), ('backstock', 'Backstock')], max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('observed_at', models.DateTimeField(help_text='When the count was taken.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_events', to='inventory.part')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-observed_at', '-id'),
                'indexes': [models.Index(fields=['part', 'kind', '-observed_at'], name='inventory_s_part_id_7cf506_idx')],
            },
        ),
    ]
