# Generated by Django 5.2.17 on 2026-08-21 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_part_manufacturer_part_manufacturer_part_num_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="group",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this appears in the guides. Blank means it does not.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="inventory.category",
            ),
        ),
    ]
