# Generated by Django 5.2.17 on 2026-08-24 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Guides category for an ungrouped part. Leave blank when a group is set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ungrouped_parts', to='inventory.category'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('group__isnull', True), ('category__isnull', True), _connector='OR'), name='part_category_only_without_group'),
        ),
    ]
